### ISSUE TITLE
強制終了

### ISSUE THREAD

**Issue by ghost** [Takesikaityo/MCPEBackup#1]
Helpを押すと強制終了します
Android Version 6.0(Minium Sdk Version 19だからバージョン関係ないと思うけど)

**Comment by Takesikaityo** [comment]
報告ありがとうございます
ログを前、取ったのですが、どうしようもなくて、
2回目以降は大丈夫だと思います

アプリをインストールしたてにcustomTabsIntentをすると落ちるログ
05-13 00:18:28.574 28886-28886/? E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.customtabs.CustomTabsIntent.launchUrl(android.content.Context, android.net.Uri)' on a null object reference
                                                         at jp.ueda.mcpebackup.MainActivity.onOptionsItemSelected(MainActivity.java:388)
                                                         at android.app.Activity.onMenuItemSelected(Activity.java:2955)
                                                         at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                                                         at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                         at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                         at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                         at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                         at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                         at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
                                                         at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                         at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                         at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                         at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
                                                         at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                         at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
                                                         at android.widget.AbsListView$PerformClick.run(AbsListView.java:3111)
                                                         at android.widget.AbsListView.onTouchUp(AbsListView.java:3960)
                                                         at android.widget.AbsListView.onTouchEvent(AbsListView.java:3725)
                                                         at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:124)
                                                         at android.view.View.dispatchTouchEvent(View.java:9348)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2563)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2569)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2270)
                                                         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2569)
                                                         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2270)
                                                         at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:1968)
                                                         at android.view.View.dispatchPointerEvent(View.java:9652)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4284)
                                                         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4111)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3710)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3676)
                                                         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3802)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3684)
                                                         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3859)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
                                                         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3710)
                                                         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3676)
                                                         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3684)
                                                         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
                                                         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6013)
                                                         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5987)
                                                         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5948)
                                                         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6116)
                                                         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                         at android.os.MessageQueue.nativePollOnce(Native Method)
                                                         at android.os.MessageQueue.next(MessageQueue.java:323)
                                                         at android.os.Looper.loop(Looper.java:135)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5513)
                                                     	at java.lang.reflect.Method.invoke(Native Method
05-13 00:18:28.574 28886-28886/? D/AndroidRuntime: Shutting down VM
05-13 00:18:28.575 28886-28886/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: jp.ueda.mcpebackup, PID: 28886
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.customtabs.CustomTabsIntent.launchUrl(android.content.Context, android.net.Uri)' on a null object reference
                                                       at jp.ueda.mcpebackup.MainActivity.onOptionsItemSelected(MainActivity.java:388)
                                                       at android.app.Activity.onMenuItemSelected(Activity.java:2955)
                                                       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
                                                       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
                                                       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
                                                       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
                                                       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
                                                       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
                                                       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
                                                       at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3111)
                                                       at android.widget.AbsListView.onTouchUp(AbsListView.java:3960)
                                                       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3725)
                                                       at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:124)
                                                       at android.view.View.dispatchTouchEvent(View.java:9348)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2563)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2569)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2270)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2569)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2270)
                                                       at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:1968)
                                                       at android.view.View.dispatchPointerEvent(View.java:9652)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4284)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4111)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3710)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3676)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3802)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3684)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3859)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3710)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3676)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3684)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3657)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6013)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5987)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5948)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6116)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                   	at android.app.ActivityThread.main(ActivityThread.
05-13 00:18:28.575 722-733/? D/ActivityManager: Prepare to send crash information Messege to SystemGaService
05-13 00:18:28.576 722-735/? D/SystemGaService: sendCrashInfoToRemote successful﻿
